- app/adapters/dmp-status.ts
- app/guid-node/niirdccore/controller.ts
- app/guid-node/niirdccore/route.ts
- app/guid-node/niirdccore/styles.scss
- app/guid-node/niirdccore/template.hbs
- app/models/dmp-status.ts
- app/router.ts
- app/serializers/dmp-status.ts
- lib/osf-components/addon/components/node-navbar/component.ts
- lib/osf-components/addon/components/node-navbar/template.hbs
#22470 (2). DMP閲覧画面の実装※表示内容はダミー
app/adapters/dmp-status.ts
app/guid-node/niirdccore/controller.ts
app/guid-node/niirdccore/route.ts
app/guid-node/niirdccore/styles.scss
app/guid-node/niirdccore/template.hbs
app/models/dmp-status.ts
app/router.ts
app/serializers/dmp-status.ts
lib/osf-components/addon/components/node-navbar/component.ts
lib/osf-components/addon/components/node-navbar/template.hbs
> #22470 (2). DMP閲覧画面の実装※表示内容はダミー

- app/guid-node/niirdccore/controller.ts
- app/guid-node/niirdccore/styles.scss
- app/guid-node/niirdccore/template.hbs
- app/models/dmp-status.ts
- translations/en-us.yml
#22470 3.(4).(2). DMP閲覧画面の実装
・DMP閲覧画面のレイアウトを修正
・DMP閲覧画面に表示するデータモデル（dmp-status）をDMPデータに合わせて階層化
・国際化一時対応（ビルドエラーが発生したため、コアアドオン以外の部分も修正）
app/guid-node/niirdccore/controller.ts
app/guid-node/niirdccore/styles.scss
app/guid-node/niirdccore/template.hbs
app/models/dmp-status.ts
translations/en-us.yml
> #22470 DMP閲覧画面のレイアウト・データモデル修正、国際化一時対応

- app/guid-node/niirdccore/controller.ts
- app/guid-node/niirdccore/template.hbs
- app/models/dmp-status.ts
#22470 3.(4).(2). DMP閲覧画面にDMP情報取得APIのスキーマ拡張を反映
・DMP情報取得APIのスキーマ拡張を反映
・controllerのgetメソッドを、クラス単位で返却するように修正
・データロード中は各table部分にLoadingIndicatorを表示するように修正
app/guid-node/niirdccore/controller.ts
app/guid-node/niirdccore/template.hbs
app/models/dmp-status.ts
> #22470 DMP閲覧画面にDMP情報取得APIのスキーマ拡張を反映

- app/guid-node/binderhub/-components/build-console/component.ts
- app/guid-node/binderhub/-components/project-editor/component.ts
- app/guid-node/binderhub/-components/project-editor/styles.scss
- app/guid-node/binderhub/-components/project-editor/template.hbs
- tests/acceptance/guid-node/binderhub-test.ts
- translations/en-us.yml
- translations/ja.yml
- Ticket: GRDM-23355, GRDM-27082
- BinderHubアドオンでrepo2dockerのProfileを指定できるように変更。
- GRDM-23355: BinderHubアドオンをrepo2dockerベースの環境設定に対応
- BinderHubの  `BINDERHUB_DEPLOYMENT_IMAGES` の `url` に `#repo2docker#r-base` などと `#repo2docker#パッケージ名,...` と指定すると、パッケージ名で指定されたdependenciesを持つ`environment.yml`を生成するように機能追加
- `install.R`の編集用に R(MRAN)パッケージ種別を追加
- GRDM-27082: Dockerfile内のパスを修正
None
None
> BinderHubアドオン repo2docker対応

- lib/osf-components/addon/components/node-navbar/component.ts
- Ticket: GRDM-27224
* ember-osf-webで作られたプロジェクト画面を参照する際に、常にIQB-RIMSアドオンとBinderHubアドオンタブが表示されてしまう(クリックしても内容を参照することはできない)バグの修正
* Promise<boolean>がTemplateで意図した解釈をされていなかったので、booleanを返すように修正
* addonsの読み込みが遅延して実施された際のため、 `this.set('プロパティ名', true|false)` を明示的に行うように修正
None
None
> Fix iqbrims and binderhub tabs

- lib/osf-components/addon/components/node-navbar/component.ts
- lib/osf-components/addon/components/node-navbar/template.hbs
- tests/integration/components/node-navbar/component-test.ts
- Ticket: GRDM-29660
IQB-RIMS他タブの挙動修正
- IQB-RIMSタブの表示についてはRDM-osf.ioと同様にIQB-RIMSアドオンがEnabledであれば(Driveの紐付けがなされていなくても)表示する
- 「分析」「登録」のタブを非表示にする
None
None
> [GRDM-29660] Fix IQB-RIMS and other tabs

- app/guid-node/binderhub/-components/project-editor/component.ts
- app/guid-node/metadata/controller.ts
- app/guid-node/metadata/template.hbs
- lib/osf-components/addon/components/node-card/component.ts
- lib/osf-components/addon/components/node-card/template.hbs
- lib/osf-components/addon/components/node-list/template.hbs
- lib/osf-components/addon/components/osf-navbar/component.ts
- lib/osf-components/addon/components/registration-report-export-button/component.ts
- lib/osf-components/addon/components/registration-report-export-button/styles.scss
- lib/osf-components/addon/components/registration-report-export-button/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/mapper/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-number-input/component.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/component.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/styles.scss
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/read-only/rdm/file-metadata-input/component.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/read-only/rdm/file-metadata-input/styles.scss
- lib/osf-components/addon/components/registries/schema-block-renderer/read-only/rdm/file-metadata-input/template.hbs
- lib/registries/addon/application/controller.ts
- translations/en-us.yml
- translations/ja.yml
- Ticket: GRDM-31485,GRDM-31190,GRDM-31645
メタデータ, BinderHubアドオンに関する複数の修正。
- [GRDM-31485] バグ RCOS環境でエクスポートボタンが押しても何も起きない の修正 - yieldを追加
- [GRDM-31190] 案内文章の修正
- [GRDM-31645] バグ Data Science NotebookにてGRDMコンテンツのディレクトリ構造が失われる の修正
None
None
> [GRDM-31485,GRDM-31190,GRDM-31645] メタデータ, BinderHubアドオンの修正

- lib/osf-components/addon/components/osf-navbar/x-links/template.hbs
- Ticket: GRDM-32978
Modify to hide search menu on nav bar when no login
Modify to hide search menu on nav bar when no login
> Modify to hide search menu on nav bar when no login

- app/guid-node/binderhub/-components/project-editor/component.ts
- Ticket: GRDM-32991
BinderHub アドオンでコピーしたファイル・フォルダの所有者が jovyan:users になるよう修正しました。
- [GRDM-32991] Dockerfile 内の COPY 命令に所有者変更オプションを追加
None
None
> [GRDM-32991] BinderHub アドオンでコピーしたファイルの所有者がjovyanになるよう修正

- lib/registries/addon/discover/route.ts
- lib/registries/addon/index/route.ts
- lib/registries/addon/index/template.hbs
- tests/engines/registries/acceptance/landing-page-test.ts
- tests/engines/registries/integration/discover/discover-test.ts
- Ticket: [GRDM-33624]
/registries ポータルサイトを停止しました。
- script タグ埋め込みの代わりに route.ts でリダイレクトするよう変更しました。
- テストを修正しました。
None
None
> [GRDM-33624] /registriesポータルサイトの停止

- app/packages/registration-schema/page-manager.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/mapper/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/component.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/styles.scss
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/template.hbs
- lib/registries/addon/drafts/draft/draft-registration-manager.ts
- translations/en-us.yml
- translations/ja.yml
メタデータ編集における登録データ画面でリロードボタンを実装しました。
- [GRDM-34189] リロードボタンを実装しました。
None
None
None
GRDM-34189
> [GRDM-34189] 登録データ画面におけるリロードボタン実装

- app/guid-node/binderhub/-components/jupyter-servers-list/component.ts
- app/guid-node/binderhub/-components/jupyter-servers-list/template.hbs
- app/guid-node/binderhub/-components/package-editor/template.hbs
- app/guid-node/binderhub/-components/project-editor/component.ts
- tests/acceptance/guid-node/binderhub-test.ts
- Ticket: GRDM-35282, GRDM-31366, GRDM-31368
BinderHubアドオンのバグ修正及びJupyterHub機能拡張に追従する変更です。
- [GRDM-35282] 基本イメージ「Python 3.9 + R 4.1.3」の場合に「pip」に追加したソフトウェアがインストールされない(バグ修正)
- [GRDM-31366] JupyterHub API 非activeなServerが取得できない (JupyterHub機能拡張)
- [GRDM-31368] 起動可能な最大サーバー数をJupyterHub APIで返す (JupyterHub機能拡張)
None
None
> [GRDM-35282, GRDM-31366, GRDM-31368] BinderHubアドオンの修正

- lib/osf-components/addon/components/new-project-modal/component.ts
- Ticket: GRDM-33518
Fix to display correct modal when failed new project creation
Fix to display correct modal when failed new project creation
> Fix to display correct modal when failed new project creation

- app/packages/registration-schema/get-schema-block-group.ts
- app/packages/registration-schema/schema-block.ts
- app/packages/registration-schema/validations.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/mapper/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/styles.scss
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/funding-stream-code-input/component.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/funding-stream-code-input/styles.scss
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/funding-stream-code-input/template.hbs
- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/japan-grant-number-input/component.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/read-only/mapper/template.hbs
- lib/osf-components/app/components/registries/schema-block-renderer/editable/rdm/funding-stream-code-input/component.js
- translations/en-us.yml
- translations/ja.yml
あわせて https://github.com/RCOSDP/RDM-osf.io/pull/398 のMergeもお願いします。
Metadata アドオンにおいてJPCOARスキーマ2.0への対応改修をしました。
- [GRDM-35861] 
- 「データ管理機関コード」 に対応しました。
- 「体系的番号におけるプログラム情報コード」に対応しました。補完も対応しました。
- メタデータ登録画面のファイルメタデータ一覧のUIを修正しました。
None
None
None
GRDM-35861
> [GRDM-35861] JPCOARスキーマ2.0への対応改修

- app/guid-node/binderhub/-components/jupyter-servers-list/component.ts
- app/guid-node/binderhub/-components/project-editor/component.ts
- app/guid-node/binderhub/controller.ts
- app/models/file-provider.ts
- app/utils/waterbutler/base.ts
- app/utils/waterbutler/file.ts
- app/utils/waterbutler/provider.ts
- app/utils/waterbutler/wrap.ts
- tests/acceptance/guid-node/binderhub-test.ts
- Ticket: GRDM-35917
BinderHubアドオンが「拡張ストレージマウント方式」機関ストレージの機関にてエラーで利用できない問題の修正。
- [GRDM-35917] osfstorageがない場合の代替ストレージの選択処理を追加しました。https://github.com/RCOSDP/RDM-osf.io/pull/405 で追加される `for_institutions` プロパティを代替ストレージの選択に使用します。また、[osf.ioのFiles API](https://developer.osf.io/#tag/Files)をサポートせず、[WaterButler API](https://waterbutler.readthedocs.io/en/latest/api.html)のみをサポートするケースを考慮し、osf.io APIではなくWaterButler APIを使用してファイル情報を取得するよう修正しました。
None
統合テストは以下の3つのストレージにおいて、BinderHubアドオンとの連携が正常に動作するかという観点で実施しております。
- デフォルトストレージ
- 機関ストレージ(一括マウント方式): 例としてAmazon S3
- 機関ストレージ(アドオン方式): 例としてOneDrive for Office365
> [GRDM-35917] BinderHubアドオンが「拡張ストレージマウント方式」機関ストレージの機関にてエラーで利用できない

- app/packages/registration-schema/get-schema-block-group.ts
- app/packages/registration-schema/schema-block.ts
メタデータアドオンにて file-title-input スキーマブロックに対応しました。
file-title-input スキーマブロックへの対応のみ
None
None
GRDM-36922
> [GRDM-36922] (rcos-release) メタデータアドオンにて file-title-input の対応 

- app/guid-node/binderhub/-components/project-editor/template.hbs
- Ticket: GRDM-37926
MRANのサービス終了(2023/7/1)にともない、これまでR(MRAN)に指定されていたパッケージは cran.ism.ac.jp から取得する形に変更します( https://github.com/RCOSDP/CS-repo2docker/pull/12 )。それに伴ってラベルをR(MRAN)からR(CRAN)に変更します。ロジックの変更はなく、表示上の変更のみです。
- [GRDM-37926] ラベルの変更
None
None
> [GRDM-37926] Fix label of R (MRAN)

- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/japan-grant-number-input/component.ts
(RCOS環境向けのPRです。)
- Ticket: GRDM-40853
メタデータ入力画面において、課題名(英語)の補完機能を提供します。
- [GRDM-40853] 体系的番号の選択時に、氏名等と同様に、課題名を `日本語|英語` で表現されているものとみなして補完を行うように修正
None
None
> [GRDM-40853] 課題名(英語)の補完

- app/guid-node/iqbrims/controller.ts
- app/guid-node/iqbrims/file-browser.ts
IQB-RIMSアドオンにて10個以上の組図ファイルアップロード時にアップロード漏れが生じる不具合を修正しました。
- アップロード時のファイル読み込みで全てのファイルを読み込むよう修正
- アップロード前・後で全てのファイルが表示されるよう修正
None
None
GRDM-40428
> [GRDM-40428] IQB-RIMSアドオンにて10個以上の組図ファイルアップロード時にアップロード漏れが生じる不具合の修正

- tests/acceptance/guid-node/iqbrims-test.ts
- Ticket: GRDM-40428
IQB-RIMS loadAllを用いる修正 https://github.com/RCOSDP/RDM-ember-osf-web/pull/100 において、Travis CIが失敗する問題の修正です。
- IQB-RIMSのテストに用いるモックオブジェクトにおいて、中身が空のフォルダもasFolder traitを指定するように修正。
None
None
> [GRDM-40428] RCOS環境テスト修正: IQB-RIMSアドオンにて10個以上の組図ファイルアップロード時にアップロード漏れが生じる不具合の修正

- app/dashboard/controller.ts
- lib/osf-components/addon/components/contributor-list/component.ts
nodesを取得する箇所でAPIからの応答に時間がかかっており、ユーザ体験に影響を与えている
- クエリセットの改良: bibliographicContributorsの取得において、queryHasManyを使用し、ページングと必要なフィールドの指定を行い、効率的にデータを取得する
- ContributorList コンポーネントの改良:コントリビュータのリストを取得時に、ページサイズを指定
これにより、最初の3人のコントリビュータが表示される
同時にリリースする必要があるプルリクエスト
https://github.com/RCOSDP/RDM-osf.io/pull/526
https://redmine.devops.rcos.nii.ac.jp/issues/44236
> ダッシュボード表示のユーザ体験向上施策

- lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/ad-metadata-input/component.ts
- Ticket: []
未病データベースのカタログ登録機能を追加（develop）
デプロイ対象環境：develop（ステージング環境）
デプロイ希望日：即日でお願いいたします。
#146の修正対応
https://github.com/RCOSDP/RDM-ember-osf-web/pull/146
誤ったファイルを適用してしまったため、差し替えになります。
A（拡張）メタデータ選択用のファイルツリーを追加する -> ファイル差し替え
　./RDM-ember-osf-web/lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/ad-metadata-input/component.ts（追加）
> 未病データベース-カタログ登録機能追加（develop）_#146バグ対応

- app/guid-node/metadata/template.hbs
- lib/registries/addon/drafts/draft/-components/register/component.ts
- lib/registries/addon/drafts/draft/-components/register/template.hbs
- translations/en-us.yml
- translations/ja.yml
- Ticket: GRDM-50321
osf.io側の修正と合わせてMergeしてください。 https://github.com/RCOSDP/RDM-osf.io/pull/601
Project Metadata関連リソースの権限調整
- Project Metadataを非管理者でも書き込み権限があれば操作できるよう、メタデータ編集画面を修正
None
None
> [GRDM-50321] Project Metadata関連リソースの権限調整 (RCOS環境)

- app/guid-node/metadata/template.hbs
- translations/en-us.yml
- translations/ja.yml
- Ticket: GRDM-50321
osf.io側の修正と合わせてMergeしてください。 https://github.com/RCOSDP/RDM-osf.io/pull/579
Project Metadata関連リソースの権限調整
- Project Metadataを非管理者でも書き込み権限があれば操作できるよう、メタデータ編集画面を修正
None
None
> [GRDM-50321] Project Metadata関連リソースの権限調整

- app/guid-node/metadata/template.hbs
- translations/en-us.yml
- translations/ja.yml
メッセージが正常に表示されていませんでしたが、そもそも不要な機能でしたので削除します。
* メタデータ一覧で親プロジェクトへのリンクを削除
None
None
> [GRDM-47137] メタデータ一覧で親プロジェクトへのリンクを削除

- app/guid-node/metadata/controller.ts
- app/guid-node/metadata/styles.scss
- app/guid-node/metadata/template.hbs
- app/utils/metadata-title-field-priority.ts
- lib/osf-components/addon/components/draft-registration-card/component.ts
- lib/osf-components/addon/components/draft-registration-card/styles.scss
- lib/osf-components/addon/components/draft-registration-card/template.hbs
- lib/osf-components/addon/components/node-card/component.ts
- lib/osf-components/addon/components/node-card/styles.scss
- lib/osf-components/addon/components/node-card/template.hbs
- lib/osf-components/addon/components/node-list/template.hbs
- lib/osf-components/addon/components/registration-report-export-button/component.ts
- lib/osf-components/addon/components/registration-report-export-button/template.hbs
- lib/registries/addon/drafts/draft/-components/register/component.ts
- lib/registries/addon/drafts/draft/-components/register/styles.scss
- lib/registries/addon/drafts/draft/-components/register/template.hbs
- lib/registries/addon/drafts/draft/-components/right-nav/template.hbs
- lib/registries/addon/drafts/draft/-components/top-nav/template.hbs
- lib/registries/addon/drafts/draft/review/template.hbs
- lib/registries/addon/drafts/draft/route.ts
- lib/registries/addon/drafts/draft/template.hbs
- mirage/config.ts
- mirage/views/metadata-node-schemas.ts
- tests/engines/registries/acceptance/draft/draft-test.ts
- translations/en-us.yml
- translations/ja.yml
(https://github.com/RCOSDP/RDM-ember-osf-web/pull/144 の適用後に適用する想定です。)
- Ticket: GRDM-41018
プロジェクトメタデータにてRegistration化をしないようにする
- プロジェクトメタデータにてRegistration化をしないように、メタデータ編集最終段階の 登録 ボタンを エクスポート ボタンに差し替え
- プロジェクトメタデータ一覧画面の メタデータ / 下書き タブを廃止。下書きは優先的に 編集可能なプロジェクトメタデータ として表示し、登録ずみデータは凍結済み(編集不可)と文言変更
- プロジェクトメタデータ各項目のタイトル表示は、 project-name-ja, project-name-en (公的資金〜メタデータ), title-of-dataset, title-of-dataset-en (未病メタデータ) の順で解決。いずれもなければ従来通りGRDMプロジェクト名
- プロジェクトメタデータ一覧画面に戻るための経路として、
-  画面上部のパンくず部分を、 プロジェクト名>プロジェクトメタデータ一覧> とし、プロジェクトメタデータ一覧に戻れるように変更
- メタデータ編集最終段階において 編集完了 ボタンを新設
None
None
> [GRDM-41018] プロジェクトメタデータにてRegistration化をしないようにする

- app/packages/registration-schema/validations.ts
- lib/osf-components/addon/components/registries/schema-block-renderer/read-only/mapper/template.hbs
- translations/en-us.yml
- translations/ja.yml
未病データベースのメタデータ登録フォームにおける入力チェックのエラーメッセージを修正。
以下の問題を修正。
- 条件付きプルダウン選択項目のエラーメッセージ定義が不足しているため、不適切なエラーメッセージが出力される
- 日本語のエラーメッセージ定義が不足しているため、日本語環境で英語のエラーメッセージが出力される
- プルダウン選択項目で選択した結果が「内容確認」ページで表示されない
None
None
> 未病データベース メタデータ登録フォームのエラーメッセージ修正
