app/locales/en/translations.ts

Enable to switch string that related Search function
Enable to switch string that related Search function
Enable to switch string that related Search function
GRDM-10559

Enable to switch string that related Search function

---

app/locales/en/translations.ts

Modify text on dashboard
Modify text on dashboard
Modify text on dashboard
GRDM-10559

Modify text on dashboard

---

config/environment.d.ts
config/environment.js
lib/osf-components/addon/components/new-project-modal/component.ts
lib/osf-components/addon/components/new-project-modal/template.hbs

Enable to hide affiliation on create new project
Enable to hide affiliation on create new project
Enable to hide affiliation on create new project
GRDM-10849

Enable to hide affiliation on create new project

---

app/dashboard/template.hbs
app/locales/en/translations.ts
app/models/node.ts
lib/osf-components/addon/components/dashboard-item/component.ts
lib/osf-components/addon/components/dashboard-item/template.hbs
tests/acceptance/dashboard-test.ts

研究者がDashboardでクォータ警告を確認する
GRDM-9456

ディスク容量のクォータ機能(Dashboard確認)

---

app/models/node.ts

Add explicit inverse
Add explicit inverse
Add explicit inverse
GRDM-13809

Add explicit inverse

---

app/application/styles.scss
app/dashboard/styles.scss

Fix location to display background image
Fix location to display background image
Fix location to display background image
GRDM-13825

Fix location to display background image

---

app/dashboard/template.hbs

RE: Modify to fill contents till reach footer
RE: Modify to fill contents till reach footer
RE: Modify to fill contents till reach footer
GRDM-16832

RE: Modify to fill contents till reach footer

---

app/guid-node/iqbrims/controller.ts
app/guid-node/iqbrims/file-browser.ts
app/guid-node/iqbrims/styles.scss
app/guid-node/iqbrims/template.hbs
app/locales/en/translations.ts
app/models/file.ts

IQB-RIMSアドオンの改修対応(2020年2月)
* ファイル投稿時のロジック改善
* ファイルアップロードのタイムアウト緩和
* ファイルビューでの名前変更時のメッセージをリソース化
None
None
None
GRDM-18125

IQB-RIMSアドオン改修(2020年2月)

---

app/locales/ja/translations.ts

Fix to enable to specify text from outer
Fix to enable to specify text from outer
Fix to enable to specify text from outer
GRDM-18793

Fix to enable to specify text from outer

---

app/locales/ja/translations.ts

minor update i18n(ja) to RDM-ember-osf-web
revise following files
app/locales/ja/translations.ts

revise ts ja sentences

---

app/locales/ja/translations.ts

minor update i18n(ja) to RDM-ember-osf-web
revise #29
(app/locales/ja/translations.ts)

revise to #29

---

app/guid-node/niirdccore/controller.ts
app/guid-node/niirdccore/styles.scss
app/guid-node/niirdccore/template.hbs
app/models/dmp-status.ts
translations/en-us.yml

データセット閲覧・編集画面を実装
* app/guid-node/niirdccore/controller.ts
* app/guid-node/niirdccore/styles.scss
* app/guid-node/niirdccore/template.hbs
* app/models/dmp-status.ts
* translations/en-us.yml

データセット閲覧・編集画面を実装

---

app/guid-node/niirdccore/controller.ts
app/guid-node/niirdccore/template.hbs
app/models/dmp-status.ts

データセットスキーマを修正（暫定対応）
* app/guid-node/niirdccore/controller.ts
* app/guid-node/niirdccore/template.hbs
* app/models/dmp-status.ts

refactor: データセットスキーマを修正（暫定対応）

---

app/guid-node/niirdccore/controller.ts
app/guid-node/niirdccore/styles.scss
app/guid-node/niirdccore/template.hbs
app/models/dmp-status.ts
translations/en-us.yml
translations/ja.yml

refactor: データセット新規作成・編集画面を修正
* app/guid-node/niirdccore/controller.ts
* app/guid-node/niirdccore/styles.scss
* app/guid-node/niirdccore/template.hbs
* app/models/dmp-status.ts
* translations/en-us.yml
* translations/ja.yml

refactor: データセット新規作成・編集画面を修正

---

app/home/-components/hero-banner/styles.scss
app/home/-components/hero-banner/template.hbs
app/home/styles.scss
app/home/template.hbs
lib/osf-components/addon/components/osf-navbar/template.hbs
tests/acceptance/logged-out-homepage-test.ts
tests/integration/components/hero-banner/component-test.ts

- Ticket: 
GRDM-25511
Modify layout
Modify layout

Modify layout

---

app/models/sparse-node.ts

- Ticket: 
GRDM-27700
Export parameters of project creator and quota, on sparse api
Export parameters of project creator and quota, on sparse api

Export parameters of project creator and quota, on sparse api

---

app/instance-initializers/intl.js

- Ticket: GRDM-27150
Fix translation when access from web browser that 'ja-jp' locale
Fix translation when access from web browser that 'ja-jp' locale

Fix translation when access from web browser that 'ja-jp' locale

---

translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-27825
Modify to hardcode Privacy Policy and Terms of Use
Modify to hardcode Privacy Policy and Terms of Use

Modify to hardcode Privacy Policy and Terms of Use

---

app/guid-node/binderhub/-components/build-console/component.ts
app/guid-node/binderhub/-components/build-console/styles.scss
app/guid-node/binderhub/-components/build-console/template.hbs
app/guid-node/binderhub/-components/jupyter-servers-list/component.ts
app/guid-node/binderhub/-components/jupyter-servers-list/styles.scss
app/guid-node/binderhub/-components/jupyter-servers-list/template.hbs
app/guid-node/binderhub/-components/project-editor/component.ts
app/guid-node/binderhub/controller.ts
app/guid-node/binderhub/template.hbs
app/models/binderhub-config.ts
tests/acceptance/guid-node/binderhub-test.ts
translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-27678,GRDM-27683,GRDM-30203
BinderHubアドオンの改善に関する修正です。
以下の点を修正しています。
- [GRDM-27678] 複数BinderHub選択機能の追加
- [GRDM-27683] ログイン情報表示機能の追加
- [GRDM-30203] Dockerfileとapt.txtを同時定義した際にUI表示とビルドされる内容に差異がある問題の修正
None
None

[GRDM-27678,GRDM-27683,GRDM-30203] BinderHub複数選択対応

---

app/guid-node/binderhub/-components/jupyter-servers-list/component.ts
app/guid-node/binderhub/-components/jupyter-servers-list/template.hbs
app/guid-node/binderhub/controller.ts

- Ticket: GRDM-30629, GRDM-30618
BinderHubアドオンのバグ修正
BinderHubアドオンに関するバグ修正を実施しました。
- JupyterHub server listに環境名・URL・最終更新が表示されない問題の修正。
- GRDMユーザを複数所持するユーザの場合、GRDMアドオンから環境が起動できない場合がある問題の修正。
None
None

[GRDM-30629,GRDM-30618] BinderHubアドオンのバグ修正

---

lib/osf-components/addon/components/registries/finalize-registration-modal/manager/component.ts
lib/registries/addon/drafts/draft/-components/register/component.ts
lib/registries/addon/drafts/draft/controller.ts

- Ticket: GRDM-28480
メタデータ登録機能への機能調整を実施しました。
metadataアドオンに以下の調整を行いました。
- ドラフトReview後の遷移先の調整
None
None

[GRDM-28480] メタデータ登録機能 機能調整

---

app/packages/registration-schema/get-schema-block-group.ts
app/packages/registration-schema/schema-block.ts
lib/osf-components/addon/components/node-card/component.ts
lib/osf-components/addon/components/node-card/template.hbs
lib/osf-components/addon/components/node-navbar/component.ts
lib/osf-components/addon/components/node-navbar/template.hbs
lib/osf-components/addon/components/osf-layout/registries-side-nav/label/component.ts
lib/osf-components/addon/components/osf-layout/registries-side-nav/label/template.hbs
lib/osf-components/addon/components/registries/registration-form-navigation-dropdown/component.ts
lib/osf-components/addon/components/registries/registration-form-navigation-dropdown/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/mapper/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-field-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-field-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-number-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/page-heading/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/page-heading/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/mapper/template.hbs
lib/osf-components/app/components/registries/schema-block-renderer/editable/rdm/e-rad-award-field-input/component.js
lib/registries/addon/drafts/draft/review/template.hbs
lib/registries/addon/index/template.hbs
tests/acceptance/view-only-link-test.ts
tests/engines/registries/acceptance/overview/overview-test.ts
translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-28480
メタデータアドオンの修正
- GRDM-28480関連修正
- 各種メタデータ入力補助への対応
- UIの多言語化
None
None

[GRDM-28480] メタデータアドオンの修正

---

translations/en-us.yml
translations/ja.yml

- Ticket:
GRDM-32453
Replace URL for support site
Replace URL for support site

Replace URL for support site

---

app/models/schema-block.ts
app/packages/registration-schema/schema-block.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/single-select-input/component.ts
translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-32614, GRDM-32169
メタデータアドオンに関する修正。
- [GRDM-32614] メタデータスキーマのデフォルトオプションの実装
- [GRDM-32169] メッセージの修正
None
None

[GRDM-32614, GRDM-32169] メタデータアドオンの修正

---

translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-35107
Replace URL for Privacy Policy
Replace URL for Privacy Policy

Replace URL for Privacy Policy

---

app/packages/registration-schema/get-schema-block-group.ts
app/packages/registration-schema/schema-block.ts

- Ticket: GRDM-34196
データNo.自動入力用に「入力」ボタンを追加しました。
- [GRDM-34196] データNo.自動入力用に「入力」ボタンを追加
None
None

[GRDM-34196] データNo.自動入力

---

app/models/schema-block.ts
app/packages/registration-schema/get-schema-block-group.ts
app/packages/registration-schema/index.ts
app/packages/registration-schema/page-manager.ts
app/packages/registration-schema/schema-block.ts
app/packages/registration-schema/validations.ts
app/validators/validate-response-format.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-title-en-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-title-ja-input/template.hbs
lib/osf-components/addon/components/validation-errors/component.ts
translations/en-us.yml
translations/ja.yml

- https://github.com/RCOSDP/RDM-osf.io/pull/452 ( https://github.com/RCOSDP/RDM-osf.io/pull/457 )に対応するember-osf-web側の対応です。
- メタデータスキーマ変更への追従
- 条件付き必須チェック(日英のうち片方が入力されていること等)への対応
None
None
- GRDM-40631

[GRDM-40631] メタデータスキーマの required_if の実装

---

app/guid-node/binderhub/-components/jupyter-servers-list/component.ts
app/guid-node/binderhub/-components/project-editor/component.ts
app/guid-node/binderhub/controller.ts
app/guid-node/package/-components/file-selector/template.hbs
app/guid-node/package/-components/files/browse/component.ts
app/guid-node/package/-components/files/browse/template.hbs
app/guid-node/package/-components/files/item/component.ts
app/guid-node/package/-components/files/item/template.hbs
app/guid-node/package/-components/files/manager/component.ts
app/guid-node/package/-components/files/manager/template.hbs
app/guid-node/package/-components/files/manager/wrapper.ts
app/guid-node/package/controller.ts
app/guid-node/package/selection.ts
app/guid-node/package/template.hbs
app/models/file-provider.ts
app/models/metadata-node-schema.ts
app/packages/registration-schema/get-schema-block-group.ts
app/utils/waterbutler/base.ts
app/utils/waterbutler/file.ts
app/utils/waterbutler/provider.ts
app/utils/waterbutler/wrap.ts
lib/osf-components/addon/components/draft-registration-card/template.hbs
lib/osf-components/addon/components/node-card/template.hbs
lib/osf-components/addon/components/registration-report-export-button/component.ts
lib/osf-components/addon/components/registration-report-export-button/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/component.ts
tests/acceptance/guid-node/binderhub-test.ts
translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-36019, GRDM-40629
WEKO3変換マッピングと、パッケージエクスポート・インポートに関する改修を行います。
osf.io側の変更 https://github.com/RCOSDP/RDM-osf.io/pull/469 と対応する修正です。
* メタデータスキーマフォーマットの拡張(array, object)に関するバグ修正
* パッケージエクスポート・インポートの改善
None
None

[GRDM-36019, GRDM-40629 他] WEKO3変換マッピング改修・パッケージエクスポート・インポート改修(RCOS環境)

---

app/packages/registration-schema/get-schema-block-group.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/component.ts

- 意図せず type: array, type: object に関するラベルが表示されてしまう不具合の修正
- 登録データ一覧表にて管理者の名前表示がobject Objectになっていた不具合の修正
None
None

メタデータアドオンに関する不具合修正

---

app/guid-node/binderhub/-components/mpm-package-editor/component.ts
app/guid-node/binderhub/-components/mpm-package-editor/styles.scss
app/guid-node/binderhub/-components/mpm-package-editor/template.hbs
app/guid-node/binderhub/-components/named-item-editor/component.ts
app/guid-node/binderhub/-components/named-item-editor/styles.scss
app/guid-node/binderhub/-components/named-item-editor/template.hbs
app/guid-node/binderhub/-components/project-editor/component.ts
app/guid-node/binderhub/-components/project-editor/template.hbs
tests/acceptance/guid-node/binderhub-test.ts
translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-40477, GRDM-41986
MATLABパッケージ選択UIを追加します。
- [GRDM-40477] MATLABパッケージ選択UIを追加
- [GRDM-41986] ラベルの修正: MRAN->CRAN
None
None

[GRDM-40477, GRDM-41986] MATLABパッケージ選択UIの実装(RCOS環境)

---

app/guid-node/binderhub/-components/mpm-package-editor/component.ts
app/guid-node/binderhub/-components/mpm-package-editor/styles.scss
app/guid-node/binderhub/-components/mpm-package-editor/template.hbs
app/guid-node/binderhub/-components/named-item-editor/component.ts
app/guid-node/binderhub/-components/named-item-editor/styles.scss
app/guid-node/binderhub/-components/named-item-editor/template.hbs
app/guid-node/binderhub/-components/project-editor/component.ts
app/guid-node/binderhub/-components/project-editor/template.hbs
tests/acceptance/guid-node/binderhub-test.ts
translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-40477, GRDM-41986
MATLABパッケージ選択UIを追加します。
- [GRDM-40477] MATLABパッケージ選択UIを追加
- [GRDM-41986] ラベルの修正: MRAN->CRAN
None
None

[GRDM-40477, GRDM-41986] MATLABパッケージ選択UIの実装

---

translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-42717
RCOS環境に対して、開発中の機能の検証のため以下の変更を実施します。
- データセットインポート機能追加
- WEKO3連携機能に関するFix
ember-osf-webでは、以下の変更を実施します。
- パッケージインポート・エクスポート機能に関するメッセージリソースの修正
- WEKO3エクスポート時のメッセージの修正
対応するosf.ioの変更は https://github.com/RCOSDP/RDM-osf.io/pull/489 です。
None
None

[GRDM-42717] データセットインポート機能追加・WEKO3連携機能に関するFix (RCOS環境)

---

app/guid-node/package/controller.ts
app/guid-node/package/template.hbs
translations/en-us.yml
translations/ja.yml

- Ticket: GRDM-42717
RCOS環境に対して、開発中の機能の検証のため以下の変更を実施します。
- WEKO3連携機能に関するインタフェース改善
osf.ioでは、以下の変更を実施します。
- WEKO3連携機能に関するインタフェース改善
対応するosf.ioの変更は ember-osf-web: https://github.com/RCOSDP/RDM-osf.io/pull/496 です。
None
None

[GRDM-42717] WEKO3連携機能に関するインタフェース改善 (RCOS環境)

---

translations/en-us.yml

- Ticket: GRDM-44921
Fix Copyright
Fix Copyright

Fix Copyright

---

app/models/schema-block.ts
app/packages/registration-schema/get-pages.ts
app/packages/registration-schema/get-schema-block-group.ts
app/packages/registration-schema/page-manager.ts
app/packages/registration-schema/schema-block.ts
app/packages/registration-schema/validations.ts
app/validators/validate-response-format.ts
lib/osf-components/addon/components/form-controls/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/mapper/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/japan-grant-number-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/pulldown-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/pulldown-input/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/pulldown-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/text/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/page-heading/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/mapper/template.hbs
lib/osf-components/addon/components/validated-input/date/component.ts
lib/osf-components/addon/components/validated-input/date/template.hbs
lib/osf-components/addon/components/validated-input/text/component.ts
lib/osf-components/addon/components/validated-input/text/template.hbs
lib/osf-components/app/components/registries/schema-block-renderer/editable/rdm/pulldown-input/component.js
lib/registries/addon/drafts/draft/styles.scss
lib/registries/addon/drafts/draft/template.hbs
translations/en-us.yml
translations/ja.yml

- Ticket: []
未病データペース用としてプロジェクトメタデータを拡張する（RCOS）
デプロイ対象環境：rcos-release
デプロイ希望日：即日でお願いいたします。
未病データベース-メタデータ機能追加（プロジェクト／ファイル） #529
https://github.com/RCOSDP/RDM-osf.io/pull/529
と同時でお願いいたします。
（１）プロジェクト名／日付の自動取得
../app/models/schema-block.ts
../app/packages/registration-schema/schema-block.ts
../lib/osf-components/addon/components/form-controls/template.hbs
../lib/osf-components/addon/components/registries/schema-block-renderer/editable/mapper/template.hbs
../lib/osf-components/addon/components/registries/schema-block-renderer/editable/text/template.hbs
../lib/osf-components/addon/components/registries/schema-block-renderer/read-only/mapper/template.hbs
../lib/osf-components/addon/components/validated-input/date/component.ts …

未病データベース-メタデータ機能追加（プロジェクト／ファイル）

---

app/guid-node/package/-components/export-target/component.ts
app/models/metadata-node-schema.ts
app/models/node-addon.ts
app/packages/registration-schema/get-schema-block-group.ts
app/packages/registration-schema/schema-block-group.ts
lib/osf-components/addon/components/node-navbar/component.ts
lib/osf-components/addon/components/node-navbar/template.hbs
lib/osf-components/addon/components/registration-report-export-button/template.hbs
lib/osf-components/addon/components/registries/page-renderer/template.hbs
lib/osf-components/addon/components/registries/review-form-renderer/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/array-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/array-input/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/array-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/file-metadata-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/text/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/editable/textarea/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/mapper/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/rdm/array-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/rdm/array-input/styles.scss
lib/osf-components/addon/components/registries/schema-block-renderer/read-only/rdm/array-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/section-heading/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/section-heading/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/subsection-heading/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/subsection-heading/template.hbs
lib/osf-components/app/components/registries/schema-block-renderer/editable/rdm/array-input/component.js
lib/osf-components/app/components/registries/schema-block-renderer/read-only/rdm/array-input/component.js
translations/en-us.yml
translations/ja.yml

osf.io側の実装は https://github.com/RCOSDP/RDM-osf.io/pull/533 です。同時にマージしてください。
- Ticket: GRDM-43834, 44417他
以下のPull Requestをrcos-releaseに適用します。
- https://github.com/RCOSDP/RDM-ember-osf-web/pull/122
- https://github.com/RCOSDP/RDM-ember-osf-web/pull/133
以下のPull RequestのSummary of Changesをご参照ください。
- https://github.com/RCOSDP/RDM-ember-osf-web/pull/122
- https://github.com/RCOSDP/RDM-ember-osf-web/pull/133
None
None

[GRDM-43834, 44417] メタデータのスキーマ・補完の強化他 / WEKO対応(バグ修正) (RCOS環境)

---

app/dashboard/controller.ts
lib/osf-components/addon/components/contributor-list/component.ts

Reverts RCOSDP/RDM-ember-osf-web#124

Revert "ダッシュボード表示のユーザ体験向上施策"

---

app/dashboard/controller.ts
lib/osf-components/addon/components/contributor-list/component.ts

同時にリリースする必要があるプルリクエスト
https://github.com/RCOSDP/RDM-osf.io/pull/541
関連プルリクエスト
https://github.com/RCOSDP/RDM-ember-osf-web/pull/124
cherry-pick 4fa9c2ad98320117665fef919c9e96b65348fd28
APIリクエストに不必要な文字が入ってしまうバグを修正
関連チケット　https://redmine.devops.rcos.nii.ac.jp/issues/45628

[GRDM 44236][bugfix]ダッシュボード表示のユーザ体験向上施策

---

app/dashboard/controller.ts
app/dashboard/template.hbs
app/models/user.ts
lib/osf-components/addon/components/new-project-modal/component.ts
lib/osf-components/addon/components/new-project-modal/template.hbs
mirage/factories/user.ts
translations/en-us.yml
translations/ja.yml

- Ticket: [GRDM-45896]
- Update UI to include checking project creation permission on the user site.
- Add new property for project creation permission.
- Update HTML and JavaScript to handle the create project error message.

[GRDM-45896] Check project creation permission

---

lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-number-input/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-title-en-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/e-rad-award-title-ja-input/template.hbs
lib/osf-components/addon/components/registries/schema-block-renderer/editable/rdm/japan-grant-number-input/component.ts

- Ticket: []
未病データベース-カタログ登録機能追加（develop）_デグレ対応
デプロイ対象環境：develop
デプロイ希望日：バグ対応のため即時でお願いいたします
R-2024-66_未病DBメタデータ登録/Dメタデータ及びAメタデータ登録機能開発
https://redmine.devops.rcos.nii.ac.jp/projects/r-2024-66_-db-d-a/issues
関連プルリクエスト
https://github.com/RCOSDP/RDM-osf.io/pull/583
https://github.com/RCOSDP/RDM-ember-osf-web/pull/146
https://github.com/RCOSDP/RDM-ember-osf-web/pull/147 (追加)
e-RAD からの、メタデータ取り込み機能の修正箇所を誤修正してしまった箇所を修正（復帰）

未病データベース-カタログ登録機能追加（develop）_デグレ対応

---

app/packages/registration-schema/schema-block.ts
lib/osf-components/addon/components/osf-layout/registries-side-nav/component.ts
lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/template.hbs
lib/registries/addon/drafts/draft/-components/right-nav/component.ts

- Ticket: []
未病データベース-カタログ登録機能追加（develop）_WEKO対応_array化mapping修正
デプロイ対象環境：develop
デプロイ希望日：即日
#606と一緒でお願いします
https://github.com/RCOSDP/RDM-osf.io/pull/606/files
(1)チェックリストのバージョン、チェック日付の確認画面の編集ボタンを非表示
./RDM-ember-osf-web/app/packages/registration-schema/schema-block.ts
./RDM-ember-osf-web/lib/osf-components/addon/components/osf-layout/registries-side-nav/template.hbs
(2)クリップボードコピーを確認画面で非表示
./RDM-ember-osf-web/lib/registries/addon/drafts/draft/-components/right-nav/component.ts
./RDM-ember-osf-web/lib/osf-components/addon/components/registries/schema-block-renderer/label/label-content/template.hbs

未病データベース-カタログ登録機能追加（develop）_WEKO対応_array化mapping修正

---

translations/en-us.yml
translations/ja.yml

http://github.com/RCOSDP/RDM-osf.io/pull/613 のRDM-ember-osf-web側の変更です。
- Ticket: GRDM-53733
アドオン名およびアイコン変更：WEKO → JAIRO Cloud
アドオン関連メッセージの変更
None
None

[GRDM-53733] アドオン名およびアイコン変更：WEKO → JAIRO Cloud
